import Head from 'next/head'
import { useState, useEffect } from 'react'

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/opensea/myCollection/id?nameCollection=kuroro-beasts-origins,gooeysp2e,otherdeed,chimera-king,kubz,doodles-official,mutant-hound-collars')
  const data = await res.json()
  console.log(data)
  return {
    props: { collections: data }
  }
}

export default function Home({ collections }) {
  // const [collections, setCollection] = useState(null)

  // useEffect(() => {
  //   async function fetchData() {
  //     const res = await fetch('http://localhost:3000/opensea/myCollection/id?nameCollection=kuroro-beasts-origins,gooeysp2e,otherdeed,chimera-king')
  //     const data = await res.json()
  //     console.log(data)
  //     setCollection(data)
  //   }
  //   fetchData()
  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {collections && <div className="bg-gradient-to-b from-blue-300 to-blue-700 via-black overflow-auto flex justify-center h-screen ">
          <table className="shadow-2xl font-mono border-2 border-cyan-200 w-6/12">
          <thead className="text-white">
            <tr>
            <th className="py-3 bg-cyan-400 whitespace-nowrap">Image</th>
              <th className="py-3 bg-cyan-400 whitespace-nowrap">Name</th>
              <th className="py-3 bg-cyan-400 whitespace-nowrap">Floor Price</th>
            </tr>
          </thead>
          <tbody className="text-cyan-500 text-center">
            {collections && collections.map(item => (
              <tr className="bg-cyan-200 cursor-pointer duration-300" key={item.name}>
                <td className="py-3 px-6 bg-gradient-to-b from-blue-300 to-blue-700 via-black whitespace-nowrap" ><img src={item.image} width="150" height="150"></img></td>
                <td className="py-3 px-6 bg-gradient-to-b from-blue-300 to-blue-700 via-black whitespace-nowrap">{item.name}</td>
                <td className="py-3 px-6 bg-gradient-to-b from-blue-300 to-blue-700 via-black whitespace-nowrap">{item.floor_price}</td>
              </tr>
            ))}
          </tbody>
        </table>
        </div>}
      </div>
    </>
  )
}
